# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WelcomeView.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WelcomeView(object):
    def setupUi(self, WelcomeView):
        WelcomeView.setObjectName("WelcomeView")
        WelcomeView.resize(1200, 900)
        WelcomeView.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(WelcomeView)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("border-image:url(./backgroung.JPG);\n"
"border-radius:25px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout.addWidget(self.frame)
        WelcomeView.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(WelcomeView)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        WelcomeView.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(WelcomeView)
        self.statusbar.setObjectName("statusbar")
        WelcomeView.setStatusBar(self.statusbar)
        self.actionLogin = QtWidgets.QAction(WelcomeView)
        self.actionLogin.setObjectName("actionLogin")
        self.actionLogout = QtWidgets.QAction(WelcomeView)
        self.actionLogout.setObjectName("actionLogout")
        self.menu.addAction(self.actionLogin)
        self.menu.addAction(self.actionLogout)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(WelcomeView)
        QtCore.QMetaObject.connectSlotsByName(WelcomeView)

    def retranslateUi(self, WelcomeView):
        _translate = QtCore.QCoreApplication.translate
        WelcomeView.setWindowTitle(_translate("WelcomeView", "WelcomeView"))
        self.menu.setTitle(_translate("WelcomeView", "登录"))
        self.actionLogin.setText(_translate("WelcomeView", "Login"))
        self.actionLogout.setText(_translate("WelcomeView", "Logout"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WelcomeView = QtWidgets.QMainWindow()
    ui = Ui_WelcomeView()
    ui.setupUi(WelcomeView)
    WelcomeView.show()
    sys.exit(app.exec_())
